#include <bits/stdc++.h>
using namespace std;

signed main() {
  int n, m;
  cin >> n;
  (n == 0) ? (m++) : (n -= (-n) & n);
  cout << ((n == 0) ? ("") : (to_string(n) + "\n"));
  (n == 0) ? (m++) : (n -= (-n) & n);
  cout << ((n == 0) ? ("") : (to_string(n) + "\n"));
  (n == 0) ? (m++) : (n -= (-n) & n);
  cout << ((n == 0) ? ("") : (to_string(n) + "\n"));
  (n == 0) ? (m++) : (n -= (-n) & n);
  cout << ((n == 0) ? ("") : (to_string(n) + "\n"));
  (n == 0) ? (m++) : (n -= (-n) & n);
  cout << ((n == 0) ? ("") : (to_string(n) + "\n"));
  (n == 0) ? (m++) : (n -= (-n) & n);
  cout << ((n == 0) ? ("") : (to_string(n) + "\n"));
  (n == 0) ? (m++) : (n -= (-n) & n);
  cout << ((n == 0) ? ("") : (to_string(n) + "\n"));
  (n == 0) ? (m++) : (n -= (-n) & n);
  cout << ((n == 0) ? ("") : (to_string(n) + "\n"));
  (n == 0) ? (m++) : (n -= (-n) & n);
  cout << ((n == 0) ? ("") : (to_string(n) + "\n"));
  (n == 0) ? (m++) : (n -= (-n) & n);
  cout << ((n == 0) ? ("") : (to_string(n) + "\n"));
  (n == 0) ? (m++) : (n -= (-n) & n);
  cout << ((n == 0) ? ("") : (to_string(n) + "\n"));
  (n == 0) ? (m++) : (n -= (-n) & n);
  cout << ((n == 0) ? ("") : (to_string(n) + "\n"));
  (n == 0) ? (m++) : (n -= (-n) & n);
  cout << ((n == 0) ? ("") : (to_string(n) + "\n"));
  (n == 0) ? (m++) : (n -= (-n) & n);
  cout << ((n == 0) ? ("") : (to_string(n) + "\n"));
  (n == 0) ? (m++) : (n -= (-n) & n);
  cout << ((n == 0) ? ("") : (to_string(n) + "\n"));
  (n == 0) ? (m++) : (n -= (-n) & n);
  cout << ((n == 0) ? ("") : (to_string(n) + "\n"));
  (n == 0) ? (m++) : (n -= (-n) & n);
  cout << ((n == 0) ? ("") : (to_string(n) + "\n"));
  (n == 0) ? (m++) : (n -= (-n) & n);
  cout << ((n == 0) ? ("") : (to_string(n) + "\n"));
  (n == 0) ? (m++) : (n -= (-n) & n);
  cout << ((n == 0) ? ("") : (to_string(n) + "\n"));
  (n == 0) ? (m++) : (n -= (-n) & n);
  cout << ((n == 0) ? ("") : (to_string(n) + "\n"));
  (n == 0) ? (m++) : (n -= (-n) & n);
  cout << ((n == 0) ? ("") : (to_string(n) + "\n"));
  (n == 0) ? (m++) : (n -= (-n) & n);
  cout << ((n == 0) ? ("") : (to_string(n) + "\n"));
  (n == 0) ? (m++) : (n -= (-n) & n);
  cout << ((n == 0) ? ("") : (to_string(n) + "\n"));
  (n == 0) ? (m++) : (n -= (-n) & n);
  cout << ((n == 0) ? ("") : (to_string(n) + "\n"));
  (n == 0) ? (m++) : (n -= (-n) & n);
  cout << ((n == 0) ? ("") : (to_string(n) + "\n"));
  (n == 0) ? (m++) : (n -= (-n) & n);
  cout << ((n == 0) ? ("") : (to_string(n) + "\n"));
  (n == 0) ? (m++) : (n -= (-n) & n);
  cout << ((n == 0) ? ("") : (to_string(n) + "\n"));
  (n == 0) ? (m++) : (n -= (-n) & n);
  cout << ((n == 0) ? ("") : (to_string(n) + "\n"));
  cout << 0 << endl;
  return 0;
}